### ISSUE TITLE
Unnecessary files layer1, layer2, layer3, scratch in service/gcs/core/gcs

### ISSUE THREAD

**Issue by jstarks** [Microsoft/opengcs#11]
Are these files used?

**Comment by gupta-ak** [comment]
Based off the names + size. I'm guessing these are files that are mounted on loopback for gcs tests. @beweedon Do you need these files or could you generate these with a script?

**Comment by beweedon** [comment]
Yeah, these are files which can be generated using a script. If we want, I could write a script and have the storage tests generate and then clean up these files on every run.

**Comment by gupta-ak** [comment]
Ideally, we should avoid binary assets in repo. I also have some test tar file that I will remove when I get the chance to create a script that generates it.

**Comment by beweedon** [comment]
Cool cool! I've been meaning to add a script for these for a while but haven't gotten around to it. Turns out adding an issue is a very good way to get me to fix a problem :)
