### ISSUE TITLE
Not updating MTU for networking in overlay mode

### ISSUE THREAD

**Issue by jstarks** [Microsoft/opengcs#115]
In the Windows GCS, we update the MTU if a non-zero EncapOverhead is passed in the adapter settings. We're not doing this here (and in fact EncapOverhead is not currently defined in the Go struct).

**Comment by jterry75** [comment]
@soccerGB - Can we get udhcpc_config.script checked in? In order to finish this it looks like I will need to pass a `mtu` option when configuring the interface.

**Comment by soccerGB** [comment]
What changes are you expecting  to add into udhcpc_config.script for this mtu issue?

**Comment by jterry75** [comment]
Unless I am misunderstanding the documentation (possible) we need to set an option when running udhcpc for `mtu` to be the `adapter.EncapOverhead` when this is `!= 0` Isn't udhcpc_config.script the place where we setup these types of options for the container network adapter?

**Comment by soccerGB** [comment]
Could you point me to the documentation that you were reading?

**Comment by jterry75** [comment]
[UDHCPC](https://udhcp.busybox.net/README.udhcpc) - The section about using client scripts like we are implies the MTU option. Again, I could be way off here but it seemed like the right track

**Comment by rn** [comment]
I wouldn't necessarily mess with the `dhcpd` configuration. To me it would make more sense to add the MTU to `prot.NetworkAdapter` and then set it [here](https://github.com/Microsoft/opengcs/blob/master/service/gcsutils/gcstools/netnsConfig.go#L100)
 with `netlink.LinkSetMTU()`. This way it'll be configured irrespective of DHCP or explicit mode.

**Comment by jterry75** [comment]
@rn - Cool! Didn't realize about the netlink helper lib. Will totally do it that way. PR on its way.
