### ISSUE TITLE
Docker is not able to build images which has FROM scratch reference

### ISSUE THREAD

**Issue by rjaini** [Microsoft/opengcs#156]
Any docker file which has FROM scratch statement is failing at add command.
For ex: 
Take docker file as below to build amazon Linux image
FROM scratch
ADD amzn-container-minimal-2017.09.0.20170930-x86_64.tar.xz /
CMD ["/bin/bash"]

The add command is failing with error:
ADD amzn-container-minimal-2017.09.0.20170930-x86_64.tar.xz /
docker : failed to copy files: svm.runProcess: command mount -t overlay 
overlay -olowerdir=,upperdir=/tmp/a3ddcb18a8db585c0472bf7512e36e0dce38c65d1d414
4f893bd6ed7baef4aaf/upper,workdir=/tmp/a3ddcb18a8db585c0472bf7512e36e0dce38c65d
1d4144f893bd6ed7baef4aaf/work 
/tmp/a3ddcb18a8db585c0472bf7512e36e0dce38c65d1d4144f893bd6ed7baef4aaf-mount 
failed with exit code 255

**Comment by rn** [comment]
quite possibly related to https://github.com/moby/moby/issues/35413

**Comment by rn** [comment]
I ca repro with:
```
FROM scratch
COPY /Dockerfile .
```
and `docker build -t foo .`

```
% docker version
Client:
 Version:      master-dockerproject-2017-11-26
 API version:  1.35
 Go version:   go1.8.5
 Git commit:   6476524
 Built:        Sun Nov 26 23:49:40 2017
 OS/Arch:      windows/amd64

Server:
 Version:      master-dockerproject-2017-11-26
 API version:  1.35 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   dfe2c02
 Built:        Sun Nov 26 23:53:37 2017
 OS/Arch:      windows/amd64
 Experimental: true

$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 8
Server Version: master-dockerproject-2017-11-26
Storage Driver: windowsfilter (windows) lcow (linux)
 LCOW:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17046 (17046.1000.amd64fre.rs_prerelease.171118-1403)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.85GiB
Name: DESKTOP-67CQHNQ
ID: Y6AG:7KSS:W6LH:UBBP:QSZ2:WFZJ:LKEC:C23K:ABST:HPRI:XYXE:XMFZ
Docker Root Dir: C:\lcow
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2017-11-29T15:50:13.2774808Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by gupta-ak** [comment]
@rn Could you try this branch: https://github.com/Microsoft/docker/tree/akagup/lcow-scratch-fix. With some fixes, I tried building some official docker images (like busybox and ubuntu) and they work fine now.

**Comment by jterry75** [comment]
@jhowardmsft - You fixed this right?

**Comment by jhowardmsft** [comment]
Yes, but still some more PRs to put in.

**Comment by rn** [comment]
I can't reproduce this anymore with:
```
docker version
Client:
 Version:       master-dockerproject-2018-03-01
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    c26f37c0
 Built: Thu Mar  1 23:50:56 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      master-dockerproject-2018-03-01
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   7459e4c
  Built:        Thu Mar  1 23:58:02 2018
  OS/Arch:      windows/amd64
  Experimental: true
```
and OpenGCS v0.3.6. Maybe it can be closed?

**Comment by jhowardmsft** [comment]
@rn no I still have a further fix to make this work. Hopefully I'll be able to submit this week

**Comment by Iristyle** [comment]
@jhowardmsft is this one still on your radar?

Trying to build some Alpine based images using multi-stage on Windows and not sure what remains based on the LCOW epic that has support listed in the backlog - https://github.com/moby/moby/issues/33850

Thanks!

**Comment by jhowardmsft** [comment]
I fixed this a long while back. Are on latest moby?

**Comment by Iristyle** [comment]
Yup - was more checking to see if this was something to still be concerned about. Thanks!

**Comment by jhowardmsft** [comment]
No, should work for LCOW. Obviously it doesn't work for WCOW though.
