### ISSUE TITLE
Implement new Protocol Negotiation

### ISSUE THREAD

**Issue by beweedon** [Microsoft/opengcs#161]
Is this a multicontainer utility VM? We'll need to determine this in order to properly handle bridge messages, resources, etc.

**Comment by jterry75** [comment]
I would lump this with the version discussion.

**Comment by beweedon** [comment]
Changed title of issue to be about implementing protocol negotiation, since that's at the heart of this.

**Comment by jterry75** [comment]
@beweedon - Want to review: [Change](https://github.com/Microsoft/opengcs/commit/5de0bffc1d65cbc5faac53439886cf6e98f5978b) and tell me if you like it. Then I can PR up the fix if you think the approach will work in the bridge.

**Comment by jterry75** [comment]
This is completed in the multicontainer branch.
