### ISSUE TITLE
Add layers separately from the container construct operation

### ISSUE THREAD

**Issue by beweedon** [Microsoft/opengcs#165]
Layers are added individually by attaching mapped virtual disks, plan9 shares, etc.

A `ModifySettings` message will then be sent with a `ModifyResourceType` of `CombinedLayers` and a `ModifyRequestType` of `Add`. It will contain a `CombinedLayers` struct specifying the layers with paths local to the utility VM (the `Path` field will no longer correspond to a lun, but an actual path).

The `ScratchPath` field will specify the path to the scratch space, and `UltimateContainerPath` will specify the requested path to the resulting union filesystem.

**Comment by jterry75** [comment]
This is completed in the multicontainer branch.
