### ISSUE TITLE
"parse of /etc/resolv.conf failed" error with Ubuntu image

### ISSUE THREAD

**Issue by AlekseyMartynov** [Microsoft/opengcs#171]
Migrated from https://github.com/moby/moby/issues/35669 as suggested in https://github.com/moby/moby/issues/35669#issuecomment-348600732

---

Using https://github.com/linuxkit/lcow#setup
Server Version: master-dockerproject-2017-11-30

```
docker run --rm -ti ubuntu bash
apt-get update
apt-get install dnsutils iputils-ping
```

/etc/resolv.conf has an entry with 2 IPs separated by space which Ubuntu cannot parse

```
cat /etc/resolv.conf
nameserver 172.28.64.1
nameserver XX.XX.XX.XX YY.YY.YY.YY
search corp.example.com
```

(XX.XX.XX.XX and YY.YY.YY.YY are LAN DNS servers)

```
nslookup any
nslookup: parse of /etc/resolv.conf failed
```

**Comment by friism** [comment]
cc @JMesser81 @kallie-b

**Comment by jterry75** [comment]
Do you just want three `nameserver` lines instead?

**Comment by AlekseyMartynov** [comment]
@jterry75 
I'd say 'Ubuntu wants'

**Comment by AlekseyMartynov** [comment]
On another machine I noticed another possible anomaly. The `search` item has has blank value which causes parse error too:

```
nameserver 172.24.224.1
nameserver 8.8.8.8 192.168.1.1
search
```

**Comment by jterry75** [comment]
The change should of addressed both issues in this thread. Please let me know if you find anything else. Thanks for the help!
