### ISSUE TITLE
GCS must support messages intended for the uvm itself

### ISSUE THREAD

**Issue by beweedon** [Microsoft/opengcs#172]
For example, `ModifySettings` messages which add a plan9 share to the utility VM using the utility VM's ID, rather than to the container's rootfs. Or graceful shutdown messages intended for the utility VM.

**Comment by beweedon** [comment]
I think we probably want operations on the utility VM like start and graceful shutdown to be a priority, since those should be simple, and are blocking removing some OS-specific code on the HCS end.

**Comment by jterry75** [comment]
This is completed in the multicontainer branch.
