### ISSUE TITLE
Kernel patches need a Signed-off-by (DCO) line

### ISSUE THREAD

**Issue by rn** [Microsoft/opengcs#28]
https://github.com/Microsoft/opengcs/blob/master/kernelconfig/4.11/patch_9pfs_vsock-transport.patch and https://github.com/Microsoft/opengcs/blob/master/kernelconfig/4.11/patch_lower-the-minimum-PMEM-size.patch as well as commits 29e6c6204845176c78c7840377a72389d188563c from https://github.com/dcui/linux.git do not have the the required Signed-off-by messages in the commit. Without we (Docker/LinuxKit) can't incorporate them into our kernel.

**Comment by dcui** [comment]
Please feel free to add "Signed-off-by: Dexuan Cui <decui@microsoft.com>" for any commit of mine (Dexuan Cui's) from my git repo https://github.com/dcui/linux.git.   :-)

**Comment by rn** [comment]
@dcui the instruction are to cherry pick your commits from your tree so I think your commits should have your DCO. I also assume you'll try to  upstream the branch so this has to be done anyway (along with detailed commit messages)

**Comment by dcui** [comment]
OK, I added my Signed-off-by and pushed it to a new branch just now: https://github.com/dcui/linux/commits/decui/hv_sock/v4.11/20170511-debug-0628-with-signed-off-by-of-dexuan-fixed

And soccerGB has helped to update the document accordingly: 
https://github.com/Microsoft/opengcs/pull/32#event-1159717050

**Comment by soccerGB** [comment]
Thanks for opening this tracking issue. It's all addressed.

**Comment by rn** [comment]
thanks for the quick turnaround
