### ISSUE TITLE
initrd size grew between 7/3 and ~7/7 by 1.5MB

### ISSUE THREAD

**Issue by jhowardmsft** [Microsoft/opengcs#42]
As sent via email to Cheng-mean, Ben, Akash & John, but no-one replied. Hence logging it here as an issue.

On 7/7 I noticed that it had increased by ~1.5MB. Currently (7/13) it is 9.5M. On 7/3 (master build 411) it was 'only' 8MB.

**Comment by gupta-ak** [comment]
It's a leftover remotefs binary. Should be fixed when remotefs is in master

**Comment by gupta-ak** [comment]
Now it's ~8MB as expected.
