### ISSUE TITLE
Network config is not transferred into container

### ISSUE THREAD

**Issue by rn** [Microsoft/opengcs#56]
I added some additional logging to the networking code 
[0001-Add-logging-to-the-networking-code.patch.txt](https://github.com/Microsoft/opengcs/files/1150315/0001-Add-logging-to-the-networking-code.patch.txt) to debug some networking issue we were seeing.

The log when running `docker.exe run --rm -ti  busybox /bin/sh` in one window and then `hcsdiag.exe read -uvm <id> /tmp/gcs.log` in another window shows after the interface was configured in the root namespace
```
time="2017-07-15T12:20:02Z" level=info msg="/go/src/github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus/entry.go:96 github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus.Entry.log() Configure network adapter 74d16c5a-de09-42f1-ba7a-26b29aed3c13[eth0]: 172.29.14.129/%!s(uint8=20) metric=1 hostip=172.29.0.1, DNSServers=172.29.0.1,10.0.1.1." 
time="2017-07-15T12:20:02Z" level=info msg="/go/src/github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus/entry.go:96 github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus.Entry.log() ifconfig eth0:
eth0      Link encap:Ethernet  HWaddr 00:15:5D:2F:67:C3  
          inet addr:172.29.14.129  Bcast:0.0.0.0  Mask:255.255.240.0
          inet6 addr: fe80::215:5dff:fe2f:67c3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
and before it is moved to the new network namespace:
```
time="2017-07-15T12:20:03Z" level=info msg="/go/src/github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus/entry.go:96 github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus.Entry.log() Move network adapter 74d16c5a-de09-42f1-ba7a-26b29aed3c13[eth0] into namespace 383" 
time="2017-07-15T12:20:03Z" level=info msg="/go/src/github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus/entry.go:96 github.com/Microsoft/opengcs/vendor/github.com/Sirupsen/logrus.Entry.log() ifconfig eth0:
eth0      Link encap:Ethernet  HWaddr 00:15:5D:2F:67:C3  
          inet addr:172.29.14.129  Bcast:0.0.0.0  Mask:255.255.240.0
          inet6 addr: fe80::215:5dff:fe2f:67c3/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:176 (176.0 B)
```

So at this point, everything looks ok. However in the container:
```
/ # ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

tunl0     Link encap:UNSPEC  HWaddr 00-00-00-00-30-30-30-30-00-00-00-00-00-00-00-00
          UP RUNNING NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
The interface is not configured.

Looking at the code in https://github.com/Microsoft/opengcs/blob/master/service/gcs/core/gcs/networking.go#L178, I don't think it is save as Go gives very little control over which OS threads code runs, while the namespace setting is tied to the namespace. See, for example, [this article](https://www.weave.works/blog/linux-namespaces-and-go-don-t-mix) for more details.

I've tried to `runtime.LockOSThread()` at the start of `moveAdapterIntoNamespace()` to no avail. I suspect that by the time that code gets executed there are already a number of threads and go routines running inside the process so this doesn't help.

It's probably safer to start a dedicated helper process to move the interface over to the new namespace. Alternatively, if the network interface is not needed in the root namespace, it would be simpler to just perform the network configuration (ie `configureNetworkAdapter()`) inside the new namespace instead of moving the config.

Full log: 
[gcs.log.txt](https://github.com/Microsoft/opengcs/files/1150318/gcs.log.txt)

**Comment by justincormack** [comment]
I dont think it is a Go issue, network namespaces should be ok in Go. However, I don't believe network configuration is transferred when interfaces are moved into a new namespace (as the config belongs to the other network stack) so you always need to configure after moving to the new namespace.

**Comment by rn** [comment]
My reading of the code is that, `eth0` get's configured in the root namespace via `configureNetworkAdapter()` and that works fine from my logging. @justincormack you are right in that the current config gets lost when the adapter is moved into the new namespace, but [`moveAdapterIntoNamespace()`](https://github.com/Microsoft/opengcs/blob/master/service/gcs/core/gcs/networking.go#L178) gathers the current configuration of `eth0`, moves the interface into the new namespace, and then re-applies the configuration in the new namespace.

The article linked in the OP seems to suggest that, even if one does a `runtime.LockOSThread()`(as suggested in the `netns` package,  it's still possible, if blocking system calls are executed, the code get executed afterwards on a different thread which is not in the new namespace. `libnetwork` also seems to bend over backwards to re-exec in some case to execute some code in the new namespace.

**Comment by justincormack** [comment]
Oh I see. Yes in that case it will be an issue, yes. Starting another process is easiest then.

**Comment by jhowardmsft** [comment]
@beweedon

**Comment by rn** [comment]
FYI, I have been working on a fix, it compiles, now I need test :)

**Comment by beweedon** [comment]
Thanks for root causing this bug! That's a really interesting (and annoying in this case) quirk of the Go runtime. Let me know if you need any help with the fix! I'd be happy to look it over at any point during development!

**Comment by rn** [comment]
I've force pushed an update. I was able to test the new binary manually on a standard Linux system (with a `veth` pair) and it works without a problem.

However, the integration with `gcs` does not work and I get an error when trying to run, but there is no meaningful error in the daemon logs. Is there way of getting at `/tmp/gcs.log`? The utility VM is already gone, so `hcsdiag` is of no help...

**Comment by beweedon** [comment]
Try setting this key to the given value (value 1). It should keep the utility VM alive even on error.
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers\Debug]
"PreserveVmOnErrorDestruct"=dword:00000001

**Comment by rn** [comment]
@beweedon I tried:
```
$regPath="HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization\Containers\Debug\"
New-Item -Path $regPath -Force
New-ItemProperty -Path $regPath -Name PreserveVmOnErrorDestruct -PropertyType DWORD -Value 1
```
And the VM does not stick around. I've also rebooted, just to make sure. I'm on insider build: 16241.1001. Any idea?

**Comment by beweedon** [comment]
Oh, ugh, that registry key might not work in this case. Do you have the ability to attach WinDbg and break on C++ errors (Debug > Event Filters, then set C++ EH to enabled)? This should break in before the VM is destructed.

**Comment by rn** [comment]
It's been two years since I last used `windbg` and that was for remote kernel/driver debug. I may need some more details...but generally yes

**Comment by rn** [comment]
NM thanks to a colleague I managed to get windbg to work and got an intriguing error. debugging

**Comment by rn** [comment]
Ah, it turns out there was an additional issue with the code, namely the netlink `Link` object may change after the interface was moved to the new namespace in https://github.com/Microsoft/opengcs/blob/master/service/gcs/core/gcs/networking.go#L208

Interfaces are indexed by number and numbers are namespaced too. With a very simple setup you may get lucky that `eth0` *happens* to be index 2 in both the root namespace *and* the new container namespace. With the LinuxKit kernel that was not the case so we gathered all the info for, say `eth0` and then tried to re-apply them to a different interface once the namespace was entered.

**Comment by beweedon** [comment]
Thanks so much for figuring out this problem! I'm reviewing your changes now!
