### ISSUE TITLE
Do we need to keep state for mapped disks and directories?

### ISSUE THREAD

**Issue by beweedon** [Microsoft/opengcs#79]
Since the GCS assumes the HCS is trusted and keeps its own state about mapped disks and directories, such as their `ContainerPath`s, does the GCS need to keep any state about which disks and directories are currently mounted into the UVM?

**Comment by jterry75** [comment]
Thinking more on this we absolutely do because we need to unmount cleanly and or skip removal of layers if unmount fails due to the issue of deleting host files from the UVM on mapped disks/directories that are not read only.
